### ISSUE TITLE
Borschik falls on external font inclusions

### ISSUE THREAD

**Issue by jifeon** [bem/borschik#93]
Thats it.
```css
@import url(//fonts.googleapis.com/css?family=Roboto:400,300,500,700&subset=latin,cyrillic);
```
in your code and borschik can't eat it. Have not found any workaround in docs.
```
Error: ENOENT, no such file or directory '/fonts.googleapis.com/cssfamily=Roboto:400,300,500,700&subset=latin,cyrillic'
    at Object.fs.openSync (fs.js:439:18)
    at Object.fs.readFileSync (fs.js:290:15)
    at exports.Tech.INHERIT.File.exports.File.INHERIT.read (/Volumes/Workspace/projects/datravel-website/application/node_modules/borschik/lib/tech.js:115:46)
    at exports.Tech.INHERIT.createFile (/Volumes/Workspace/projects/datravel-website/application/node_modules/borschik/lib/tech.js:26:41)
    at exports.Tech.INHERIT.File.exports.File.INHERIT.child (/Volumes/Workspace/projects/datravel-website/application/node_modules/borschik/lib/tech.js:152:68)
    at exports.Tech.base.Tech.inherit.File.exports.File.base.File.inherit.processInclude (/Volumes/Workspace/projects/datravel-website/application/node_modules/borschik/lib/techs/css.js:91:30)
    at exports.Tech.INHERIT.File.exports.File.INHERIT.process (/Volumes/Workspace/projects/datravel-website/application/node_modules/borschik/lib/tech.js:138:26)
    at exports.Tech.INHERIT.process (/Volumes/Workspace/projects/datravel-website/application/node_modules/borschik/lib/tech.js:34:56)
    at Cmd.<anonymous> (/Volumes/Workspace/projects/datravel-website/application/node_modules/borschik/lib/coa.js:137:38)
    at /Volumes/Workspace/projects/datravel-website/application/node_modules/borschik/node_modules/coa/lib/cmd.js:483:22
```

**Comment by tadatuta** [comment]
@jifeon please provide your `.borschik` config

**Comment by zxqfox** [comment]
Hm, it's like loading from cdn. Did you tried to quote that url?

**Comment by jifeon** [comment]
@tadatuta 
```json
{
  "paths": {
    "../img/sprites/": "/",
    "./": "/"
  },
  "freeze_paths": {
    "public/freezing/**/*.js": "public/frozen",
    "public/freezing/**/*.css": "public/frozen",
    "public/freezing/**/*.png": "public/frozen"
  }
}
```

@zxqfox Yep, the same for:
```css
@import url("//fonts.googleapis.com/css?family=Roboto:400,300,500,700&subset=latin,cyrillic");
```
